# Generated by Django 5.2.5 on 2026-09-06 18:39

import apps.attendance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_studentenrollment_academics_s_tenant__a1d42a_idx_and_more'),
        ('students', '0002_student_students_st_tenant__b74932_idx_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.classgroup')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused'), ('SICK', 'Sick'), ('SCHOOL_ACTIVITY', 'School activity')], max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructional_days', models.JSONField(default=apps.attendance.models.default_instructional_days)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['tenant', 'class_group', 'session_date'], name='attendance__tenant__dc205c_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('tenant', 'class_group', 'session_date'), name='unique_attendance_session_per_class_per_day'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'student', 'session'], name='attendance__tenant__d3d857_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'session', 'student'), name='unique_attendance_record_per_session_per_student'),
        ),
        migrations.AddConstraint(
            model_name='attendancesetup',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_attendance_setup_per_tenant'),
        ),
    ]
