# Generated by Django 5.2.5 on 2026-09-06 16:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('recipient', models.CharField(max_length=120)),
                ('message_type', models.CharField(max_length=60)),
                ('context', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'available_at'], name='notificatio_tenant__055578_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_notification_idempotency_per_tenant')],
            },
        ),
    ]
