# Generated by Django 5.2.5 on 2026-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invite_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
