# Generated by Django 5.2.5 on 2026-09-06 12:15
#
# Risk: HIGH per docs/architecture/migration-safety.md's blanket presumption
# for finance/ledger tables. Actual execution risk is low pre-production:
# StudentLedgerEntry has zero production rows, so no backfill is needed and
# the constraint swap is effectively instantaneous. If this table is ever
# populated before a similar constraint change, split the CheckConstraint
# swap into NOT VALID + VALIDATE CONSTRAINT (expand/migrate/contract)
# instead of a single atomic replace.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_allocationreversal_payment_paymentallocation_receipt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentledgerentry',
            name='ledger_entry_has_source',
        ),
        migrations.AddField(
            model_name='studentledgerentry',
            name='payment_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.paymentallocation'),
        ),
        migrations.AddField(
            model_name='studentledgerentry',
            name='allocation_reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.allocationreversal'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_allocation__isnull', False)), fields=('tenant', 'payment_allocation'), name='unique_payment_allocation_ledger_entry'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation_reversal__isnull', False)), fields=('tenant', 'allocation_reversal'), name='unique_allocation_reversal_ledger_entry'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('invoice__isnull', False), ('credit_note__isnull', False), ('payment_allocation__isnull', False), ('allocation_reversal__isnull', False), _connector='OR'), name='ledger_entry_has_source'),
        ),
    ]
