# Generated by Django 5.2.5 on 2026-09-06 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_extend_studentledgerentry_for_payments'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('REVERSED', 'Reversed')], default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reversal_number', models.CharField(max_length=60)),
                ('reason', models.CharField(max_length=240)),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reversal_number'), name='unique_payment_reversal_number_per_tenant')],
            },
        ),
    ]
