# Generated by Django 5.2.5 on 2026-09-06 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_status_paymentreversal'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_reference', models.CharField(blank=True, default='', max_length=240)),
                ('external_transaction_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=20)),
                ('ignored_reason', models.CharField(blank=True, default='', max_length=240)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payment', to='finance.payment')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_payments', to='finance.paymentmethod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'received_at'], name='finance_inc_tenant__8baa26_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_transaction_id'), name='unique_incoming_payment_transaction_per_tenant'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='incoming_payment_amount_positive')],
            },
        ),
    ]
