# Generated by Django 5.2.5 on 2026-09-06 14:24

import apps.finance.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_incomingpayment'),
        ('students', '0002_student_students_st_tenant__b74932_idx_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_type', models.CharField(choices=[('C2B_VALIDATION', 'C2B validation'), ('C2B_CONFIRMATION', 'C2B confirmation'), ('STK_CALLBACK', 'STK callback')], max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_callback_logs', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaStkPushRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(max_length=40)),
                ('merchant_request_id', models.CharField(max_length=60)),
                ('checkout_request_id', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_code', models.CharField(blank=True, default='', max_length=10)),
                ('result_description', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='finance.incomingpayment')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='finance.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='finance_mpe_tenant__e835f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'checkout_request_id'), name='unique_stk_checkout_request_per_tenant'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='mpesa_stk_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='TenantMpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('shortcode', models.CharField(max_length=20)),
                ('consumer_key', apps.finance.fields.EncryptedCharField(max_length=500)),
                ('consumer_secret', apps.finance.fields.EncryptedCharField(max_length=500)),
                ('passkey', apps.finance.fields.EncryptedCharField(max_length=500)),
                ('callback_token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.paymentmethod')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_mpesa_configuration_per_tenant')],
            },
        ),
    ]
