from django.urls import path

from .api import (
    AllocationReversalView,
    AssignmentListCreateView,
    CreditNoteListCreateView,
    FeeCategoryListCreateView,
    FeeItemListCreateView,
    FeeStructureApproveView,
    FeeStructureLineCreateView,
    FeeStructureListCreateView,
    FinanceSetupView,
    IncomingPaymentIgnoreView,
    IncomingPaymentListCreateView,
    IncomingPaymentMatchView,
    InvoiceGenerateView,
    InvoiceIssueView,
    InvoiceListView,
    PaymentAllocateView,
    PaymentDetailView,
    PaymentListCreateView,
    PaymentReversalView,
    StudentFinanceView,
    StudentLedgerListView,
)
from .mpesa_api import (
    MpesaC2BConfirmationView,
    MpesaC2BValidationView,
    MpesaCallbackTokenRotateView,
    MpesaConfigurationView,
    MpesaStkCallbackView,
    StkPushInitiateView,
)


urlpatterns = [
    path("setup/", FinanceSetupView.as_view(), name="finance-setup"),
    path("fee-categories/", FeeCategoryListCreateView.as_view(), name="fee-category-list"),
    path("fee-items/", FeeItemListCreateView.as_view(), name="fee-item-list"),
    path("fee-structures/", FeeStructureListCreateView.as_view(), name="fee-structure-list"),
    path("fee-structures/<uuid:structure_id>/lines/", FeeStructureLineCreateView.as_view(), name="fee-structure-line-create"),
    path("fee-structures/<uuid:structure_id>/approve/", FeeStructureApproveView.as_view(), name="fee-structure-approve"),
    path("student-fee-assignments/", AssignmentListCreateView.as_view(), name="student-fee-assignment-list"),
    path("student-fee-assignments/<uuid:assignment_id>/generate-invoice/", InvoiceGenerateView.as_view(), name="invoice-generate"),
    path("invoices/", InvoiceListView.as_view(), name="invoice-list"),
    path("invoices/<uuid:invoice_id>/issue/", InvoiceIssueView.as_view(), name="invoice-issue"),
    path("credit-notes/", CreditNoteListCreateView.as_view(), name="credit-note-list"),
    path("payments/", PaymentListCreateView.as_view(), name="payment-list"),
    path("payments/<uuid:payment_id>/", PaymentDetailView.as_view(), name="payment-detail"),
    path("payments/<uuid:payment_id>/allocate/", PaymentAllocateView.as_view(), name="payment-allocate"),
    path("payments/<uuid:payment_id>/reverse/", PaymentReversalView.as_view(), name="payment-reverse"),
    path("payment-allocations/<uuid:allocation_id>/reverse/", AllocationReversalView.as_view(), name="payment-allocation-reverse"),
    path("ledger-entries/", StudentLedgerListView.as_view(), name="ledger-entry-list"),
    path("incoming-payments/", IncomingPaymentListCreateView.as_view(), name="incoming-payment-list"),
    path("incoming-payments/<uuid:incoming_payment_id>/match/", IncomingPaymentMatchView.as_view(), name="incoming-payment-match"),
    path("incoming-payments/<uuid:incoming_payment_id>/ignore/", IncomingPaymentIgnoreView.as_view(), name="incoming-payment-ignore"),
    path("students/<uuid:student_id>/finance/", StudentFinanceView.as_view(), name="student-finance"),
    path("mpesa-config/", MpesaConfigurationView.as_view(), name="mpesa-config"),
    path("mpesa-config/rotate-callback-token/", MpesaCallbackTokenRotateView.as_view(), name="mpesa-config-rotate-token"),
    path("mpesa/stk-push/", StkPushInitiateView.as_view(), name="mpesa-stk-push-initiate"),
    path("mpesa/<str:callback_token>/c2b/validation/", MpesaC2BValidationView.as_view(), name="mpesa-c2b-validation"),
    path("mpesa/<str:callback_token>/c2b/confirmation/", MpesaC2BConfirmationView.as_view(), name="mpesa-c2b-confirmation"),
    path("mpesa/<str:callback_token>/stk/callback/", MpesaStkCallbackView.as_view(), name="mpesa-stk-callback"),
]