# Generated by Django 5.2.5 on 2026-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentenrollment_academics_s_tenant__a1d42a_idx_and_more'),
        ('assessments', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gradingscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'academic_level'), name='unique_active_grading_scheme_per_level'),
        ),
    ]
