# Generated by Django 5.2.5 on 2026-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['tenant', 'student', 'academic_year'], name='academics_s_tenant__a1d42a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['tenant', 'class_group', 'status'], name='academics_s_tenant__6d7977_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'student', 'academic_year'), name='unique_student_enrollment_per_year'),
        ),
    ]
