# Generated by Django 5.2.5 on 2026-09-06 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=120)),
                ('resource_id', models.CharField(max_length=120)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id', '-occurred_at'], name='activity_ac_tenant__fc976a_idx')],
            },
        ),
    ]
