import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, NumberInput, Stack } from "@mantine/core";
import { api, Page } from "../api/client";
import { useAccess, useAuth } from "../app/auth";
import { ActionDialog } from "../components/ActionDialog";
import { DocumentsPanel } from "../features/documents";
import { notify } from "../components/notifications/notify";
import { Empty, ErrorState, go, Icon, Loading, PageHeader, StatusBadge } from "../components/ui";

type Row=Record<string,unknown>;
const money=new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0});
const pretty=(key:string)=>key.replace(/_/g," ").replace(/\b\w/g,(x:string)=>x.toUpperCase());
function display(value:unknown):React.ReactNode{if(value===null||value===undefined||value==="")return <span className="quiet">—</span>;if(typeof value==="boolean")return <StatusBadge value={value}/>;if(Array.isArray(value))return value.length?`${value.length} items`:<span className="quiet">None</span>;if(typeof value==="object"){const r=value as Row;return String(r.name??r.label??r.username??r.id??"Details")};const text=String(value);if(/^(active|inactive|draft|issued|paid|pending|approved|published|failed|rejected|open|submitted|processed|unmatched|matched)$/i.test(text))return <StatusBadge value={text}/>;return text}

export function LoginPage(){const {login}=useAuth();const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await login(username,password);go("/")}catch(caught){setError(caught instanceof Error?caught.message:"Sign in failed")}finally{setBusy(false)}}return <main className="auth-page"><section className="auth-brand"><div className="brand"><div className="brand-mark">S</div><div><strong>Scholaris</strong><small>School ERP</small></div></div><div><p className="eyebrow light">One school. One operating picture.</p><h1>Run the school day with confidence.</h1><p>Student records, learning, staff and finance stay connected under one secure tenant context.</p></div><div className="auth-proof"><span>Tenant isolated</span><span>Permission controlled</span><span>Audit ready</span></div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div><p className="eyebrow">Welcome back</p><h2>Sign in to your workspace</h2><p>Use the account provided by your school administrator.</p></div>{error&&<div className="form-error" role="alert">{error}</div>}<label>Username or email<input autoFocus autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button primary wide" disabled={busy}>{busy?"Signing in…":"Sign in"}</button><p className="auth-help">Invited to a school? Use the secure link in your invitation email.</p></form></section></main>}

export function InvitePage(){const token=new URLSearchParams(location.search).get("token")??"";const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await api<{token:string}>("/auth/invites/accept/",{method:"POST",tenant:false,body:JSON.stringify({token,password})});localStorage.setItem("school-erp-token",r.token);location.href="/"}catch(e){setMessage(e instanceof Error?e.message:"Invitation could not be accepted")}finally{setBusy(false)}}return <main className="center-page"><form className="auth-form card" onSubmit={submit}><div className="brand standalone"><div className="brand-mark">S</div><strong>Scholaris</strong></div><div><p className="eyebrow">School invitation</p><h2>Set up your access</h2><p>Choose a password if this is your first Scholaris account. Existing users may leave it blank.</p></div>{!token&&<div className="form-error">This invitation link has no token.</div>}{message&&<div className="form-error">{message}</div>}<label>Password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary wide" disabled={!token||busy}>{busy?"Activating…":"Accept invitation"}</button></form></main>}

function Metric({label,value,meta,tone="blue"}:{label:string;value:React.ReactNode;meta:string;tone?:string}){return <article className="metric card"><span className={`metric-icon ${tone}`}><Icon name={tone==="green"?"check":tone==="amber"?"inbox":"chart"}/></span><div><p>{label}</p><strong>{value}</strong><small>{meta}</small></div></article>}

export function DashboardPage(){const {session}=useAuth();const {can}=useAccess();const students=useQuery({queryKey:["students-count"],queryFn:()=>api<Page<Row>>("/students/",{params:{page_size:1}}),enabled:can("students.view")});const invoices=useQuery({queryKey:["invoice-count"],queryFn:()=>api<Page<Row>>("/finance/invoices/",{params:{page_size:5}}),enabled:can("finance.invoice.view")});const payments=useQuery({queryKey:["payment-count"],queryFn:()=>api<Page<Row>>("/finance/payments/",{params:{page_size:5}}),enabled:can("finance.payment.view")});const incoming=useQuery({queryKey:["incoming-count"],queryFn:()=>api<Page<Row>>("/finance/incoming-payments/",{params:{page_size:5}}),enabled:can("finance.reconciliation.view")});return <><PageHeader eyebrow={session?.active_tenant?.name} title={`Good day, ${session?.user.name.split(" ")[0]}`} description="Here is the current operating picture for your school." action={<button className="button secondary" onClick={()=>location.reload()}>Refresh</button>}/><div className="metrics"><Metric label="Students" value={students.data?.count??"—"} meta="Visible in your campus scope"/><Metric label="Invoices" value={invoices.data?.count??"—"} meta="Billing records" tone="green"/><Metric label="Payments" value={payments.data?.count??"—"} meta="Recorded transactions"/><Metric label="Needs matching" value={incoming.data?.count??"—"} meta="Incoming payment queue" tone="amber"/></div><div className="dashboard-grid"><section className="card panel-card"><div className="card-heading"><div><h2>Recent invoices</h2><p>Latest billing activity</p></div><button className="text-link" onClick={()=>go("/finance/invoices")}>View all →</button></div><MiniRows rows={invoices.data?.results??[]} primary="invoice_number" secondary="status" value="total"/></section><section className="card panel-card"><div className="card-heading"><div><h2>Work queue</h2><p>Items that may need attention</p></div></div><div className="queue-list"><button onClick={()=>go("/finance/incoming")}><span className="queue-icon amber"><Icon name="inbox"/></span><span><strong>Incoming payments</strong><small>Review and match receipts</small></span><b>{incoming.data?.count??"—"}</b></button><button onClick={()=>go("/communications/inbox")}><span className="queue-icon blue"><Icon name="bell"/></span><span><strong>Notifications</strong><small>Open your personal inbox</small></span><b>→</b></button><button onClick={()=>go("/leave")}><span className="queue-icon green"><Icon name="calendar"/></span><span><strong>Leave requests</strong><small>Review current requests</small></span><b>→</b></button></div></section></div></>}

function MiniRows({rows,primary,secondary,value}:{rows:Row[];primary:string;secondary:string;value:string}){if(!rows.length)return <Empty title="No recent activity" message="New records will appear here."/>;return <div className="mini-rows">{rows.slice(0,5).map((row,i)=><div key={String(row.id??i)}><span><strong>{display(row[primary])}</strong><small>{display(row[secondary])}</small></span><b>{value==="total"?money.format(Number(row[value]??0)):display(row[value])}</b></div>)}</div>}

export type ResourceConfig={title:string;description:string;endpoint:string;permission?:string;columns:string[];eyebrow?:string;actionLabel?:string};
export function ResourcePage({config}:{config:ResourceConfig}){const [page,setPage]=useState(1);const [search,setSearch]=useState("");const query=useQuery({queryKey:[config.endpoint,page,search],queryFn:()=>api<Page<Row>|Row[]>(config.endpoint,{params:{page,search:search||undefined}})});const data=Array.isArray(query.data)?query.data:query.data?.results??[];const count=Array.isArray(query.data)?query.data.length:query.data?.count??0;return <><PageHeader eyebrow={config.eyebrow} title={config.title} description={config.description} action={config.actionLabel?<button className="button primary">+ {config.actionLabel}</button>:undefined}/><section className="card data-card"><div className="table-tools"><label className="search-field"><Icon name="search"/><input placeholder={`Search ${config.title.toLowerCase()}`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><span>{count.toLocaleString()} records</span></div>{query.isLoading?<Loading/>:query.isError?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:!data.length?<Empty/>:<div className="table-scroll"><table><thead><tr>{config.columns.map(column=><th key={column}>{pretty(column)}</th>)}</tr></thead><tbody>{data.map((row,index)=><tr key={String(row.id??index)}>{config.columns.map(column=><td key={column}>{display(row[column])}</td>)}</tr>)}</tbody></table></div>} {!Array.isArray(query.data)&&query.data&&<div className="pagination"><button disabled={!query.data.previous} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={!query.data.next} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section></>}

export function StudentsPage(){const [page,setPage]=useState(1);const [search,setSearch]=useState("");const query=useQuery({queryKey:["students",page,search],queryFn:()=>api<Page<Row>>("/students/",{params:{page,search:search||undefined}})});return <><PageHeader eyebrow="Student records" title="Students" description="Find a learner and open their complete school record."/><section className="card data-card"><div className="table-tools"><label className="search-field"><Icon name="search"/><input placeholder="Search by name or admission number" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{query.data?.count??0} students</span></div>{query.isLoading?<Loading/>:query.isError?<ErrorState error={query.error}/>:!query.data?.results.length?<Empty title="No students found"/>:<div className="student-cards">{query.data.results.map(student=><button key={String(student.id)} onClick={()=>{sessionStorage.setItem(`student:${student.id}`,JSON.stringify(student));go(`/students/${student.id}`)}}><span className="student-avatar">{String(student.full_name??"ST").split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span><strong>{display(student.full_name)}</strong><small>{display(student.admission_number)} · {display(student.campus)}</small></span><StatusBadge value={String(student.status??"Active")}/><b>›</b></button>)}</div>}<div className="pagination"><button disabled={!query.data?.previous} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={!query.data?.next} onClick={()=>setPage(p=>p+1)}>Next</button></div></section></>}

export function StudentPage({id}:{id:string}){const student=JSON.parse(sessionStorage.getItem(`student:${id}`)??"{}") as Row;const {can,moduleEnabled}=useAccess();const tabs=["Overview",...(moduleEnabled("finance")&&can("finance.student_account.view")?["Fees"]:[]),...(moduleEnabled("attendance")&&can("attendance.record.view")?["Attendance"]:[]),...(moduleEnabled("assessments")&&can("assessment.record.view")?["Assessments"]:[]),...(moduleEnabled("documents")&&can("students.document.view")?["Documents"]:[]),"Guardians","Activity"];const [tab,setTab]=useState("Overview");const finance=useQuery({queryKey:["student-finance",id],queryFn:()=>api<Row>(`/finance/students/${id}/finance/`),enabled:tab==="Fees"});const attendance=useQuery({queryKey:["student-attendance",id],queryFn:()=>api<Row>(`/attendance/students/${id}/summary/`),enabled:tab==="Attendance"});const assessments=useQuery({queryKey:["student-assessment",id],queryFn:()=>api<Row>(`/assessments/students/${id}/summary/`),enabled:tab==="Assessments"});return <><button className="back-link" onClick={()=>go("/students")}>← Student directory</button><section className="record-head"><div className="student-avatar large">{String(student.full_name??"ST").split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><p className="eyebrow">{String(student.admission_number??"Student record")}</p><h1>{String(student.full_name??"Student")}</h1><p>{String(student.campus??"Campus not assigned")}</p></div><StatusBadge value={String(student.status??"Active")}/></section><nav className="record-tabs">{tabs.map(name=><button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}>{name}</button>)}</nav><section className="card record-body">{tab==="Overview"&&<div className="overview-grid"><Info label="Admission number" value={student.admission_number}/><Info label="Campus" value={student.campus}/><Info label="Current status" value={student.status}/></div>}{tab==="Fees"&&<JsonPanel query={finance}/>} {tab==="Documents"&&<DocumentsPanel basePath="/students" ownerId={id} viewPermission="students.document.view" managePermission="students.document.manage" can={can}/>} {tab==="Attendance"&&<JsonPanel query={attendance}/>} {tab==="Assessments"&&<JsonPanel query={assessments}/>} {(tab==="Guardians"||tab==="Activity")&&<Empty title={`${tab} is not available yet`} message={`The backend does not currently expose a ${tab.toLowerCase()} endpoint.`}/>}</section></>}

export function StaffPage(){const query=useQuery({queryKey:["employees"],queryFn:()=>api<Page<Row>>("/staff/employees/")});return <><PageHeader eyebrow="Staff & HR" title="Employees" description="Open an employee record to manage employment, qualifications, documents and leave."/><section className="card data-card">{query.isLoading?<Loading/>:query.isError?<ErrorState error={query.error}/>:!query.data?.results.length?<Empty/>:<div className="student-cards">{query.data.results.map(employee=><button key={String(employee.id)} onClick={()=>go(`/staff/${employee.id}`)}><span className="student-avatar">{`${String(employee.first_name??"").slice(0,1)}${String(employee.last_name??"").slice(0,1)}`}</span><span><strong>{String(employee.first_name??"")} {String(employee.last_name??"")}</strong><small>{display(employee.employee_number)} · {display(employee.job_title)}</small></span><StatusBadge value={String(employee.status??"Active")}/><b>›</b></button>)}</div>}</section></>}

export function EmployeePage({id}:{id:string}){const {can}=useAccess();const detail=useQuery({queryKey:["employee",id],queryFn:()=>api<Row>(`/staff/employees/${id}/`)});const tabs=["Overview","Qualifications","Documents",...(can("leave.request.view")||can("leave.balance.adjust")?["Leave"]:[]),...(can("staff.user_link.manage")?["User access"]:[])];const [tab,setTab]=useState("Overview");const qualifications=useQuery({queryKey:["employee-qualifications",id],queryFn:()=>api<Page<Row>|Row[]>(`/staff/employees/${id}/qualifications/`),enabled:tab==="Qualifications"});const leave=useQuery({queryKey:["employee-leave",id],queryFn:()=>api<Row>(`/leave/employees/${id}/balance/`),enabled:tab==="Leave"});if(detail.isLoading)return <Loading label="Opening employee record"/>;if(detail.isError)return <ErrorState error={detail.error}/>;const employee=detail.data??{};return <><button className="back-link" onClick={()=>go("/staff")}>← Employee directory</button><section className="record-head"><div className="student-avatar large">{`${String(employee.first_name??"").slice(0,1)}${String(employee.last_name??"").slice(0,1)}`}</div><div><p className="eyebrow">{String(employee.employee_number??"Employee record")}</p><h1>{String(employee.first_name??"")} {String(employee.last_name??"")}</h1><p>{String(employee.job_title??"Job title not assigned")} · {String(employee.department??"No department")}</p></div><StatusBadge value={String(employee.status??"Active")}/></section><nav className="record-tabs">{tabs.map(name=><button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}>{name}</button>)}</nav><section className="card record-body">{tab==="Overview"&&<div className="overview-grid">{["employment_type","hire_date","campus","email","phone_number","user_account"].map(key=><Info key={key} label={pretty(key)} value={employee[key]}/>)}</div>}{tab==="Qualifications"&&<JsonPanel query={qualifications}/>} {tab==="Documents"&&<DocumentsPanel basePath="/staff/employees" ownerId={id} viewPermission="staff.view" managePermission="staff.manage" can={can}/>} {tab==="Leave"&&<JsonPanel query={leave}/>} {tab==="User access"&&<div className="overview-grid"><Info label="Linked account" value={employee.user_account}/><Info label="Account management" value="Available to authorized administrators"/></div>}</section></>}
function Info({label,value}:{label:string;value:unknown}){return <div className="info-block"><small>{label}</small><strong>{display(value)}</strong></div>}
function JsonPanel({query}:{query:{isLoading:boolean;isError:boolean;error:unknown;data?:unknown}}){if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState error={query.error}/>;if(!query.data)return <Empty/>;const value=query.data as Row;const entries=Array.isArray(value)?value:Object.entries(value);return <div className="overview-grid">{Array.isArray(entries)&&entries.slice(0,12).map((entry,index)=>Array.isArray(entry)?<Info key={entry[0]} label={pretty(entry[0])} value={entry[1]}/>:<Info key={index} label={`Record ${index+1}`} value={entry}/>)}</div>}

export function SetupPage(){const {can}=useAccess();const setups=[{name:"Finance",endpoint:"/finance/setup/",permission:"finance.setup.view"},{name:"Leave",endpoint:"/leave/setup/",permission:"leave.setup.view"},{name:"Documents",endpoint:"/documents/setup/",permission:"documents.setup.view",managePermission:"documents.setup.manage"}].filter(x=>can(x.permission));return <><PageHeader eyebrow="Administration" title="Module setup" description="Configuration is grouped by operational domain. Communications setup has moved to Communication → Providers & channels."/><div className="setup-grid">{setups.map(x=><SetupCard key={x.name} {...x}/>)}</div></>}
function SetupCard({name,endpoint,managePermission}:{name:string;endpoint:string;managePermission?:string}){
	const {can}=useAccess();
	const qc=useQueryClient();
	const q=useQuery({queryKey:[endpoint],queryFn:()=>api<Row>(endpoint)});
	const [editOpen,setEditOpen]=useState(false);
	const [retentionDays,setRetentionDays]=useState<number|"">("");
	const canManage=!!managePermission&&can(managePermission);
	const save=useMutation({
		mutationFn:()=>api<Row>(endpoint,{method:"PATCH",body:JSON.stringify({default_retention_days:retentionDays===""?null:retentionDays})}),
		onSuccess:()=>{void qc.invalidateQueries({queryKey:[endpoint]});setEditOpen(false);notify.success(`${name} setup updated`)},
		onError:error=>notify.error(`${name} setup could not be updated`,error),
	});
	return <section className="card setup-card">
		<div className="card-heading"><div><h2>{name}</h2><p>Current configuration</p></div>{canManage&&<button className="button secondary" onClick={()=>{setRetentionDays((q.data?.default_retention_days as number|null)??"");setEditOpen(true)}}>Edit</button>}</div>
		{q.isLoading?<Loading label="Loading setup"/>:q.isError?<ErrorState error={q.error}/>:<div className="config-list">{Object.entries(q.data??{}).slice(0,6).map(([k,v])=><div key={k}><span>{pretty(k)}</span><strong>{display(v)}</strong></div>)}</div>}
		{canManage&&<ActionDialog open={editOpen} title={`Edit ${name.toLowerCase()} setup`} confirmLabel="Save" busy={save.isPending} onClose={()=>setEditOpen(false)} onSubmit={e=>{e.preventDefault();save.mutate()}}>
			<Stack gap="sm">
				{save.error&&<Alert color="red" variant="light">{save.error instanceof Error?save.error.message:"The action failed"}</Alert>}
				<NumberInput label="Default retention (days)" description="Leave blank for no automatic expiry." min={1} value={retentionDays} onChange={value=>setRetentionDays(value===""?"":Number(value))}/>
			</Stack>
		</ActionDialog>}
	</section>;
}

export function PlatformHome(){const modules=useQuery({queryKey:["platform-modules"],queryFn:()=>api<Row[]>("/platform/modules/",{tenant:false})});const [form,setForm]=useState({name:"",slug:"",admin_email:""});const [result,setResult]=useState("");async function provision(e:FormEvent){e.preventDefault();try{const data=await api<Row>("/platform/tenants/",{method:"POST",tenant:false,body:JSON.stringify(form)});setResult(`Created ${String(data.name)} (${String(data.slug)})`);setForm({name:"",slug:"",admin_email:""})}catch(e){setResult(e instanceof Error?e.message:"Provisioning failed")}}return <><PageHeader eyebrow="Platform administration" title="Tenant operations" description="Provision schools and control the modules available to each tenant."/><div className="platform-grid"><section className="card panel-card"><div className="card-heading"><div><h2>Provision a school</h2><p>Creates the tenant and first administrator invitation.</p></div></div><form className="form-grid" onSubmit={provision}><label>School name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Tenant slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")})} required/></label><label className="span-two">First administrator email<input type="email" value={form.admin_email} onChange={e=>setForm({...form,admin_email:e.target.value})} required/></label><div className="span-two form-actions">{result&&<p>{result}</p>}<button className="button platform-button">Provision school</button></div></form></section><section className="card panel-card"><div className="card-heading"><div><h2>Module catalogue</h2><p>Capabilities available to subscription plans.</p></div></div>{modules.isLoading?<Loading/>:modules.isError?<ErrorState error={modules.error}/>:<div className="module-list">{modules.data?.map(module=><div key={String(module.code)}><span className="metric-icon violet"><Icon name="layers"/></span><span><strong>{display(module.label)}</strong><small>{display(module.code)}</small></span></div>)}</div>}</section></div></>}

export const resources:Record<string,ResourceConfig>={
 "/finance/fees":{eyebrow:"Finance · Setup",title:"Fee structures",description:"Approved charging schedules by academic year and level.",endpoint:"/finance/fee-structures/",columns:["name","academic_year","academic_level","is_approved","created_at"]},
 "/finance/invoices":{eyebrow:"Finance · Billing",title:"Invoices",description:"Issued and draft student charges.",endpoint:"/finance/invoices/",columns:["invoice_number","student","status","total","issued_at"]},
 "/finance/payments":{eyebrow:"Finance · Collections",title:"Payments",description:"Recorded receipts and allocation status.",endpoint:"/finance/payments/",columns:["receipt_number","student","amount","unallocated_amount","received_at"]},
 "/finance/incoming":{eyebrow:"Finance · Reconciliation",title:"Incoming payments",description:"Review money received before it reaches a student account.",endpoint:"/finance/incoming-payments/",columns:["provider","external_reference","payer_phone","amount","status","received_at"]},
 "/finance/mpesa":{eyebrow:"Finance · M-Pesa",title:"Callback inbox",description:"Verify and process provider callbacks with a complete audit trail.",endpoint:"/finance/mpesa/callbacks/",columns:["event_type","status","merchant_request_id","checkout_request_id","received_at"]},
 "/attendance":{eyebrow:"Academics",title:"Attendance sessions",description:"Open registers, record attendance and submit completed sessions.",endpoint:"/attendance/sessions/",columns:["attendance_date","class_group","status","opened_by","submitted_at"]},
 "/assessments":{eyebrow:"Academics",title:"Assessments",description:"Marks entry, review, approval and publication.",endpoint:"/assessments/assessments/",columns:["name","class_group","subject","status","assessment_date"]},
 "/timetable":{eyebrow:"Academics",title:"Timetable",description:"Class, teacher and room schedules for the active term.",endpoint:"/timetable/entries/",columns:["day_of_week","period","class_group","subject","teacher","room"]},
 "/staff":{eyebrow:"Staff & HR",title:"Employees",description:"Employment records within your campus scope.",endpoint:"/staff/employees/",columns:["employee_number","full_name","job_title","department","status"]},
 "/leave":{eyebrow:"Staff & HR",title:"Leave requests",description:"Employee requests and approval workflow.",endpoint:"/leave/requests/",columns:["employee","leave_type","starts_on","ends_on","status"]},
 "/administration/users":{eyebrow:"Administration",title:"Users",description:"Tenant memberships, roles and campus scope.",endpoint:"/tenancy/memberships/",columns:["user","role","campus","is_active","joined_at"]},
 "/administration/roles":{eyebrow:"Administration",title:"Roles & permissions",description:"Define the actions each school role can perform.",endpoint:"/tenancy/roles/",columns:["name","permissions"]},
 "/platform/plans":{eyebrow:"Platform administration",title:"Subscription plans",description:"Module bundles assigned to schools.",endpoint:"/platform/plans/",columns:["name","module_codes","is_default","is_active","created_at"]},
 "/platform/audit":{eyebrow:"Platform administration",title:"Platform audit trail",description:"Recorded cross-tenant administrative actions.",endpoint:"/platform/audit-events/",columns:["actor","action","resource_type","resource_id","created_at"]},
};

export function MissingPage(){return <><PageHeader title="Page not found" description="This workspace does not exist or is not available to your account."/><div className="card"><Empty title="Nothing at this address" message="Use the navigation to return to an available module."/></div></>}
