# Generated by Django 5.2.5 on 2026-09-07 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('retention_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'retention_expires_at'], name='documents_d_tenant__411da7_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'storage_key'), name='unique_storage_key_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_document_setup_per_tenant')],
            },
        ),
    ]
