# Generated by Django 5.2.5 on 2026-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'status'], name='students_st_tenant__b74932_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'campus', 'status'], name='students_st_tenant__627791_idx'),
        ),
    ]
