# Generated by Django 5.2.5 on 2026-09-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('students', '0002_student_students_st_tenant__b74932_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document'),
        ),
    ]
