# Generated by Django 5.2.5 on 2026-09-07 08:09

import apps.leave.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApprovalWorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leave.leaveapprovalworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_days', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='staff.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('stage_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=240)),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.role')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=apps.leave.models.default_working_days)),
                ('leave_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('leave_year_start_day', models.PositiveSmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('default_annual_entitlement_days', models.PositiveSmallIntegerField()),
                ('requires_balance', models.BooleanField(default=True)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('allows_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_types', to='leave.leaveapprovalworkflow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_year', models.PositiveSmallIntegerField()),
                ('entry_type', models.CharField(choices=[('ENTITLEMENT', 'Entitlement'), ('CARRY_FORWARD', 'Carry forward'), ('CONSUMED', 'Consumed'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('days', models.SmallIntegerField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_ledger_entries', to='staff.employee')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leavetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leaveapprovalworkflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_leave_workflow_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='leaveapprovalworkflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_stage_sequence_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='leaverequestapproval',
            constraint=models.UniqueConstraint(fields=('leave_request', 'sequence'), name='unique_stage_sequence_per_request'),
        ),
        migrations.AddConstraint(
            model_name='leavesetup',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_leave_setup_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_leave_type_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='leave_leave_tenant__88ff5f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveledgerentry',
            index=models.Index(fields=['tenant', 'employee', 'leave_type', 'leave_year'], name='leave_leave_tenant__da13bc_idx'),
        ),
    ]
